server:
  port: 8003

# mybatis的配置
mybatis:
  type-aliases-package: cn.guardwhy.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/cn/guardwhy/mapper/*.xml
  
#spring的相关配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 数据源
    driver-class-name: org.gjt.mm.mysql.Driver   # mysql驱动
    url: jdbc:mysql://localhost:3306/db_springclound3?useUnicode=true&characterEncoding=utf8&useSSL=false #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5  #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5  #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间

#Eureka的信息，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8003 #修改eureka上的默认描述

#info 配置
info:
  app.name: guardwhy-springcloud
  company.name: www.guardwhy.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}



